Sabiendo que $\log_{2}(1/p(s))$

1. Sea S un conjunto finito cualquiera que contiene iguales cantidades de dos clases de objetos distintos, digamos A y B. ¿Cuánto es la entropía H(S) de S ? Explique en términos de cantidad de bits esperados por objeto si su resultado tiene sentido.

$$
H(s) = P(s) - \log_{2}(P(s))
$$
Se sabe que P(s) es 50% para cualquiera de los dos objetos, por enunciado

$$
H(s) = 0.5 * - \log_{2}(0.5) \\
H(s) = 0.5 * - - 1 \\
H(s) = 0.5 \\
\therefore \text{se espera que cada objeto se exprese con } \sim\text{0.5 bits}
$$

2. Trate de justificar o refutar intuitivamente la siguiente frase: "a más entropía menos similitud (pureza)".

Se sabe que entre mayor entropía es mayor la cantidad de bits que se utiliza para representar el objeto. Esto implica que en el árbol de decisiones va a mostrarse más alejado de la raíz. Como está más alejado de la raíz entonces es menos similar al otro. Concluyendo que en efecto entre más entropía menos similitud.

3. Usando el dataset mamíferos.csv, calcule el feature que produce el split (partición) del dataset de  mínima entropía, entre los features predictores vuela, ponehuevos, nada. Recuerde que nuestro feature target es mamífero. Indique la partición en cada caso. Note que ese feature sería la primera pregunta de un árbol de decisión basado en esos datos.

In [2]:
import numpy as np
import math

In [3]:
data = np.loadtxt('./drive-download-20240304T191658Z-001/mamiferos.csv', dtype=str, delimiter=',')

In [4]:
data.shape

(8, 5)

In [5]:
features_index = {n:i for i, n in enumerate(data[0,1:])}
print(features_index)

{'vuela': 0, 'ponehuevos': 1, 'nada': 2, 'mamifero': 3}


In [6]:
def column(f):
    return features_index[f]

In [7]:
info_as_int = data[1:, 1:].astype(int)
print(info_as_int)

[[0 1 0 0]
 [0 0 1 1]
 [0 0 1 1]
 [0 1 1 0]
 [1 1 1 0]
 [0 1 1 1]
 [1 0 0 1]]


In [8]:
animals = data[1:, 0]
total_animals = len(animals)

In [9]:
vuela = info_as_int[:, column('vuela')]
ponehuevos = info_as_int[:, column('ponehuevos')]
nada = info_as_int[:, column('nada')]
mamifero = info_as_int[:, column('mamifero')]


In [10]:
def p(s, total):
    return len(s) / total

In [11]:
def H(s, total):
    p_s = p(s, total)
    if (p_s != 0):
        return p_s - math.log2(p_s)
    return None

In [12]:
animals[(vuela == 1)]

array(['pato', 'murcielago'], dtype='<U12')

In [13]:
print('Vuela', H(animals[(vuela == 1)], total_animals))
print('Ponehuevos', H(animals[(ponehuevos == 1)], total_animals))
print('Nada', H(animals[(nada == 1)], total_animals))
print('Mamiferos', H(animals[(mamifero == 1)], total_animals))

Vuela 2.0930692077718898
Ponehuevos 1.3787834934861758
Nada 1.199712541455956
Mamiferos 1.3787834934861758


In [14]:
temp_total = len(animals[(nada == 1)])
print('Nada y Vuela', H(animals[((nada & mamifero) & vuela == 1)], total_animals - temp_total))
print('Nada y Ponehuevos', H(animals[((nada & mamifero) & ponehuevos == 1)], total_animals - temp_total))

Nada y Vuela None
Nada y Ponehuevos 1.5
