In [2]:
import numpy as np

In [3]:
data = np.loadtxt('./drive-download-20240304T191658Z-001/mamiferos.csv', dtype=str, delimiter=',')
print(data)

[['animal' 'vuela' 'ponehuevos' 'nada' 'mamifero']
 ['gallina' '0' '1' '0' '0']
 ['perro' '0' '0' '1' '1']
 ['gato' '0' '0' '1' '1']
 ['pinguino' '0' '1' '1' '0']
 ['pato' '1' '1' '1' '0']
 ['ornitorrinco' '0' '1' '1' '1']
 ['murcielago' '1' '0' '0' '1']]


In [4]:
data.shape

(8, 5)

In [5]:
data[0]

array(['animal', 'vuela', 'ponehuevos', 'nada', 'mamifero'], dtype='<U12')

In [6]:
features_index = {n:i for i, n in enumerate(data[0, 1:])}
print(features_index)

{'vuela': 0, 'ponehuevos': 1, 'nada': 2, 'mamifero': 3}


In [7]:
def column(f):
    return features_index[f]

In [8]:
column('vuela')

0

In [9]:
x = data[1:, 1:].astype(int)
print(x)

[[0 1 0 0]
 [0 0 1 1]
 [0 0 1 1]
 [0 1 1 0]
 [1 1 1 0]
 [0 1 1 1]
 [1 0 0 1]]


In [10]:
ponehuevos = x[:, column('ponehuevos')]
print(ponehuevos)

[1 0 0 1 1 1 0]


In [11]:
nada = x[:, column('nada')]
print(nada)

[0 1 1 1 1 1 0]


In [12]:
ponehuevos & nada

array([0, 0, 0, 1, 1, 1, 0])

In [13]:
a = np.array([12, 33, 45])

print(a)

print(a + 100)

print(a + a)

[12 33 45]
[112 133 145]
[24 66 90]


In [14]:
animals = data[1:, 0]

In [17]:
animals[(ponehuevos & nada == 0)]

array(['gallina', 'perro', 'gato', 'murcielago'], dtype='<U12')